name: PR Check
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  pr_check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Check formatting
        run: npm run prettier

      - name: Check linting
        run: npm run lint
